dist: xenial
sudo: require
language: cpp
compiler: gcc

#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq

install:
  - sudo apt-get install lcov libcurl4-openssl-dev libssl-dev uuid-dev libjsoncpp-dev

script:
  ./unit_test.sh
  ./generate_code_cov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
